stages:
  - build
  - deploy

build:
  stage: build
  image: node:22-alpine
  script:
    - yarn install
    - VITE_BASE_URL=https://api.tabihunt.kz yarn build
  artifacts:
    paths:
      - dist
    expire_in: 1 hour

deploy:
  stage: deploy
  tags:
    - deploy
  only:
    - main
  script:
    - rm -rf /var/www/html/cabinet.tabihunt.kz/*
    - mkdir -p /var/www/html/cabinet.tabihunt.kz
    - cp -r dist/* /var/www/html/cabinet.tabihunt.kz
