image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login  -u $CI_REGISTRY_USER --password-stdin registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t ${IMAGE_TAG} .
    - docker push ${IMAGE_TAG}

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - cd /opt/tabihunt-portal
    - docker pull ${IMAGE_TAG}
    - docker compose up -d
